# Generated by Django 5.1.2 on 2024-10-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_employeemodel_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
    ]
