# Generated by Django 5.1.2 on 2024-10-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('empapp', '0004_alter_employeemodel_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeModel',
            new_name='Employee',
        ),
    ]
